services:
  flask-prod:
    profiles: ["prod"]
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 192.168.9.45
    networks:
      - server_net
    build: .
    ports:
      - "8080:8080"
    env_file:
      - env/.env.prod
  flask-dev:
    profiles: ["dev"]
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 192.168.9.45
    networks:
      - server_net
    build: .
    ports:
      - "8080:8080"
    env_file:
      - env/.env.dev
  redis:
    profiles: ["dev", "prod"]
    image: "redis:7.2.4-alpine3.19"
    networks:
      - server_net

networks:
  server_net:
    driver: bridge
