
networks:
  internal:
    driver: bridge


services:
  wireguard:
    build:
      context: ./wireguard
      dockerfile: Dockerfile
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./wireguard/wg0.conf.template:/etc/wireguard/wg0.conf.template
    restart: unless-stopped
    environment:
      - WG_PORT=51820
      - PRIVATE_KEY=${PRIVATE_KEY}
    expose: 
      - "51820"
    env_file:
      - .env
    networks:
      - internal
    
  caddy:
    image: caddy:latest 
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - /etc/letsencrypt:/etc/letsencrypt 
      - "80:80" # HTTP
      - "443:443"  # HTTPS
    restart: unless-stopped
    environment:
      - ACME_AGREE=true 
    networks:
      - internal
    
  cloud_webserver_v2:
    build:
      context: ../cloud_webserver_v2
    container_name: cloud_webserver_v2
    expose:
      - "8080"  # Port that Caddy will use
    env_file:
      - ../cloud_webserver_v2/.env
    restart: unless-stopped
    networks:
      - internal
