FROM golang:1.23

RUN apt-get update && apt-get install -y \
    libhdf5-serial-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN go install github.com/air-verse/air@v1.61.7

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

ENTRYPOINT ["air"]
