name: build docker image and publish to ghcr

on:
  push:
    branches:
      - main
      - mps-fix

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./cloud_webserver_v2
          file: ./cloud_webserver_v2/Dockerfile
          push: true
          tags: |
            ghcr.io/hytech-racing/data_acq_cloud:latest
            ghcr.io/hytech-racing/data_acq_cloud:${{ steps.vars.outputs.SHORT_SHA }}

